version: '{branch}-{build}'
image: Visual Studio 2017
branches:
  only:
  - master
  - /[0-9]+\.[0-9]+(\.[xX])?/
configuration: Release
assembly_info:
  patch: true
  file: '**\*AssemblyInfo.cs'
  assembly_version: $(AssemblyBaseVersion).0
  assembly_file_version: $(AssemblyBaseVersion).{build}
  assembly_informational_version: $(PackageVersion)
environment:
  XamarinMSBuildExtensionsPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild
install:
- cmd: >-
    cd .\build
- ps: >-
    ./SetBuildEnv.ps1

    cd ..
build_script:
- ps: >-
    Write-Host "Configuration=${env:CONFIGURATION}"

    cd ./build

    ./Build.ps1

    if ( $LastExitCode -ne 0 )
    {
        Write-Error "Failed to build."
        exit 1
    }

    appveyor PushArtifact "../dist/MsgPack.Cli.${env:PackageVersion}.nupkg"

    if ( $LastExitCode -ne 0 )
    {
        Write-Error "Failed to publish nupkg."
        exit 1
    }

    appveyor PushArtifact "../dist/MsgPack.Cli.${env:PackageVersion}.symbols.nupkg"

    if ( $LastExitCode -ne 0 )
    {
        Write-Error "Failed to publish symbol nupkg."
        exit 1
    }

    appveyor PushArtifact "../dist/MsgPack.Cli.${env:PackageVersion}.zip"

    if ( $LastExitCode -ne 0 )
    {
        Write-Error "Failed to publish zip."
        exit 1
    }

    cd ..
deploy:
- provider: Environment
  name: msgpack-cli-nuget
  on:
    APPVEYOR_REPO_TAG: true
- provider: Environment
  name: msgpack-cli-github
  on:
    APPVEYOR_REPO_TAG: true
