version: '{branch}-{build}'
branches:
  only:
  - master
  - 0.7
configuration: Release
assembly_info:
  patch: true
  file: '**\*AssemblyInfo.cs'
  assembly_version: $(AssemblyBaseVersion).0
  assembly_file_version: $(AssemblyBaseVersion).{build}
  assembly_informational_version: $(PackageVersion)
environment:
  ANDROID_HOME: C:\android-sdk-windows
install:
- ps: >-
    cd ./build

    ./SetBuildEnv.ps1

    cd ..
build_script:
- ps: >-
    Write-Host "Configuration=${env:CONFIGURATION}"

    cd ./build

    ./Build.ps1

    appveyor PushArtifact "../dist/MsgPack.Cli.${env:PackageVersion}.nupkg"

    appveyor PushArtifact "../dist/MsgPack.Cli.${env:PackageVersion}.symbols.nupkg"

    appveyor PushArtifact "../dist/MsgPack.Cli.${env:PackageVersion}.zip"

    cd ..
deploy:
- provider: Environment
  name: msgpack-cli-nuget
  on:
    APPVEYOR_REPO_TAG: true
- provider: Environment
  name: msgpack-cli-github
  on:
    APPVEYOR_REPO_TAG: true
